project_id = "evkbhalknerpptiofwsi"

[functions.track-visit]
verify_jwt = false

[functions.auto-empty-trash]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.record-login]
verify_jwt = false
