
-- Add SEO override columns to blog_posts
ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS seo_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_keywords TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_canonical_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_image TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_image TEXT DEFAULT NULL;

-- Add SEO override columns to notices
ALTER TABLE public.notices
  ADD COLUMN IF NOT EXISTS seo_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_keywords TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_canonical_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_image TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_image TEXT DEFAULT NULL;

-- Add SEO override columns to study_materials
ALTER TABLE public.study_materials
  ADD COLUMN IF NOT EXISTS seo_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_keywords TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_canonical_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_og_image TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_title TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_description TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS seo_twitter_image TEXT DEFAULT NULL;
